"""
I/O from and to the CUED members database.

"""
import csv

# Field names in departmental CSV file.
_CSV_FIELD_NAMES = [
    'crsid', 'status', 'surname', 'fnames', 'pref_name', 'room', 'phone',
    'arrived', 'start_date', 'end_date', 'div_id', 'role_course',
    'host_supervisor', 'rg_name'
]

def write_members_to_csv(csvfile, queryset):
    """
    Write the members returned in a queryset to a CSV file in the manner
    generated by the Department at:

        http://www-itsd.eng.cam.ac.uk/datadownloads/

    Fields not stored in the cuedmembers database are left blank.

    csvfile can be any object which supports a file-object-like write() method.

    """
    writer = csv.DictWriter(csvfile, _CSV_FIELD_NAMES)
    writer.writeheader()

    # Tell the query set which related fields we'll be using.
    related_queryset = queryset.select_related(
        'user', 'research_group', 'research_group__division'
    )

    for member in related_queryset:
        has_rg = member.research_group is not None
        div_id = member.research_group.division.letter if has_rg else None
        writer.writerow({
            'crsid': member.user.username,
            'surname': member.user.last_name,
            'fnames': member.first_names,
            'pref_name': member.user.first_name,
            'div_id': div_id,
            'rg_name': member.research_group.name if has_rg else None,
        })
