# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-07 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0002_add_unique_constraint_to_relationship'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together=set([]),
        ),
    ]
