# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 19:34
from __future__ import unicode_literals

import os

from django.db import migrations
from django.core import serializers

fixture_dir = os.path.abspath(
    os.path.join(os.path.dirname(__file__), '..', 'fixtures',
                 'cuedmembers'))
fixture_filename = 'research_groups.json'

def load_fixture(apps, schema_editor):
    fixture_file = os.path.join(fixture_dir, fixture_filename)
    with open(fixture_file, 'rb') as fixture:
        objects = serializers.deserialize(
            'json', fixture, ignorenonexistent=True)
        for obj in objects:
            obj.save()

def unload_fixture(apps, schema_editor):
    "Brutally deleting all entries for this model..."
    MyModel = apps.get_model("cuedmembers", "ResearchGroup")
    MyModel.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('cuedmembers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture)
    ]
