# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuedmembers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('S', 'Staff'), ('P', 'Postgrad'), ('V', 'Visitor')], max_length=1)),
                ('start_on', models.DateField()),
                ('end_on', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='member',
            old_name='departed_on',
            new_name='last_inactive_on',
        ),
        migrations.RemoveField(
            model_name='member',
            name='expected_departure_on',
        ),
        migrations.AddField(
            model_name='member',
            name='perferred_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='research_group',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='division',
            field=models.CharField(blank=True, choices=[('A', 'Energy, Fluids and Turbomachinery'), ('B', 'Electrical Engineering'), ('C', 'Mechanics, Materials and Design'), ('D', 'Civil Engineering'), ('E', 'Manufacturing and Management'), ('F', 'Information Engineering'), ('', 'No Division')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='status',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='cuedmembers.Member'),
        ),
    ]
