# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuedmembers', '0002_auto_20160425_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterField(
            model_name='member',
            name='perferred_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
