# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuedmembers', '0003_auto_20160425_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='perferred_name',
            new_name='first_names',
        ),
    ]
