# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 12:16
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=1)),
                ('arrived_on', models.DateField()),
                ('departed_on', models.DateField(null=True)),
                ('expected_departure_on', models.DateField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorshipPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seeking_mentor', models.BooleanField()),
                ('is_seeking_mentee', models.BooleanField()),
                ('staff_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mentoring.StaffMember')),
                ('mentee_requirements', models.TextField(blank=True)),
                ('mentor_requirements', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MentorshipRelationships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_on', models.DateField()),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('mentee_staff_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='mentoring.StaffMember')),
                ('mentor_staff_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentees', to='mentoring.StaffMember')),
            ],
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='departed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='expected_departure_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorshiprelationships',
            name='ended_by_staff_memebr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_relationships_ended', to='mentoring.StaffMember'),
        ),
        migrations.AlterField(
            model_name='mentorshiprelationships',
            name='mentee_staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='mentoring.StaffMember'),
        ),
        migrations.AlterField(
            model_name='mentorshiprelationships',
            name='mentor_staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentees', to='mentoring.StaffMember'),
        ),
        migrations.RenameModel(
            old_name='MentorshipRelationships',
            new_name='MentorshipRelationship',
        ),
        migrations.AlterModelOptions(
            name='mentorshippreferences',
            options={'verbose_name_plural': 'mentorship preferences'},
        ),
        migrations.RenameField(
            model_name='mentorshiprelationship',
            old_name='ended_by_staff_memebr',
            new_name='ended_by',
        ),
        migrations.RenameField(
            model_name='mentorshiprelationship',
            old_name='mentee_staff_member',
            new_name='mentee',
        ),
        migrations.RenameField(
            model_name='mentorshiprelationship',
            old_name='mentor_staff_member',
            new_name='mentor',
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField()),
                ('mentor_response', models.CharField(choices=[('A', 'Accept'), ('D', 'Decline')], max_length=1)),
                ('mentee_response', models.CharField(choices=[('A', 'Accept'), ('D', 'Decline')], max_length=1)),
                ('cancelled_on', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_created', to='mentoring.StaffMember')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_invitations', to='mentoring.StaffMember')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_invitations', to='mentoring.StaffMember')),
                ('relationship', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentoring.MentorshipRelationship')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held_on', models.DateField()),
                ('approximate_duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MR', 'Mentor'), ('ME', 'ME')], max_length=1)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.StaffMember')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='mentoring.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held_on', models.DateField()),
                ('details_url', models.URLField(blank=True)),
                ('attendees', models.ManyToManyField(to='mentoring.StaffMember')),
            ],
        ),
        migrations.AlterModelManagers(
            name='staffmember',
            managers=[
                ('current_members', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='mentorshippreferences',
            name='staff_member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership_preferences', to='mentoring.StaffMember'),
        ),
        migrations.RemoveField(
            model_name='mentorshippreferences',
            name='id',
        ),
        migrations.AlterField(
            model_name='mentorshippreferences',
            name='is_seeking_mentee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mentorshippreferences',
            name='is_seeking_mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mentorshippreferences',
            name='staff_member',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mentorship_preferences', serialize=False, to='mentoring.StaffMember'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='is_current',
            field=models.BooleanField(),
        ),
        migrations.AlterModelManagers(
            name='staffmember',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='mentorshiprelationship',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentorshiprelationship',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_relationships', to='mentoring.StaffMember'),
        ),
        migrations.AlterField(
            model_name='mentorshiprelationship',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_relationships', to='mentoring.StaffMember'),
        ),
        migrations.RenameField(
            model_name='staffmember',
            old_name='is_current',
            new_name='is_active',
        ),
    ]
