# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 16:17
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuedmembers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField()),
                ('mentor_response', models.CharField(choices=[('A', 'Accept'), ('D', 'Decline')], max_length=1)),
                ('mentee_response', models.CharField(choices=[('A', 'Accept'), ('D', 'Decline')], max_length=1)),
                ('cancelled_on', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held_on', models.DateField()),
                ('approximate_duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='MentorshipPreferences',
            fields=[
                ('member', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mentorship_preferences', serialize=False, to='cuedmembers.Member')),
                ('is_seeking_mentor', models.BooleanField(default=False)),
                ('is_seeking_mentee', models.BooleanField(default=False)),
                ('mentor_requirements', models.TextField(blank=True)),
                ('mentee_requirements', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'mentorship preferences',
            },
        ),
        migrations.CreateModel(
            name='MentorshipRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_on', models.DateField()),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_relationships_ended', to='cuedmembers.Member')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_relationships', to='cuedmembers.Member')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_relationships', to='cuedmembers.Member')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held_on', models.DateField()),
                ('details_url', models.URLField(blank=True)),
                ('attendees', models.ManyToManyField(to='cuedmembers.Member')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.MentorshipRelationship'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_created', to='cuedmembers.Member'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_invitations', to='cuedmembers.Member'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_invitations', to='cuedmembers.Member'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='relationship',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentoring.MentorshipRelationship'),
        ),
    ]
