# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together=set([('mentor', 'mentee')]),
        ),
    ]
