# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0002_mentorshipsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipRelationships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiated_on', models.DateField()),
                ('finished_on', models.DateField(null=True)),
                ('finished_by_staff_member', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_relationship_finished', to='mentoring.StaffMember')),
                ('initiated_by_staff_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_relationship_initiated', to='mentoring.StaffMember')),
                ('mentee_staff_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='mentoring.StaffMember')),
                ('mentor_staff_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentees', to='mentoring.StaffMember')),
            ],
        ),
    ]
