# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0002_auto_20160424_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='mentee',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='mentorshippreferences',
            name='member',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
        migrations.DeleteModel(
            name='MentorshipPreferences',
        ),
    ]
