# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0003_mentorshiprelationships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshiprelationships',
            name='finished_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='departed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='expected_departure_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
