# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0003_auto_20160424_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingevent',
            name='attendees',
        ),
        migrations.DeleteModel(
            name='TrainingEvent',
        ),
    ]
