# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0004_auto_20160422_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorshiprelationships',
            old_name='finished_on',
            new_name='ended_on',
        ),
        migrations.RenameField(
            model_name='mentorshiprelationships',
            old_name='initiated_on',
            new_name='started_on',
        ),
        migrations.RemoveField(
            model_name='mentorshiprelationships',
            name='finished_by_staff_member',
        ),
        migrations.RemoveField(
            model_name='mentorshiprelationships',
            name='initiated_by_staff_member',
        ),
        migrations.AddField(
            model_name='mentorshiprelationships',
            name='ended_by_staff_memebr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_relationships_ended', to='mentoring.StaffMember'),
        ),
        migrations.AddField(
            model_name='mentorshipsettings',
            name='mentee_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentorshipsettings',
            name='mentor_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mentorshiprelationships',
            name='mentee_staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='mentoring.StaffMember'),
        ),
        migrations.AlterField(
            model_name='mentorshiprelationships',
            name='mentor_staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentees', to='mentoring.StaffMember'),
        ),
    ]
