# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0005_auto_20160422_1715'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MentorshipSettings',
            new_name='MentorshipPreferences',
        ),
        migrations.RenameModel(
            old_name='MentorshipRelationships',
            new_name='MentorshipRelationship',
        ),
        migrations.AlterModelOptions(
            name='mentorshippreferences',
            options={'verbose_name_plural': 'mentorship preferences'},
        ),
    ]
