# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0006_auto_20160422_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorshiprelationship',
            old_name='ended_by_staff_memebr',
            new_name='ended_by',
        ),
        migrations.RenameField(
            model_name='mentorshiprelationship',
            old_name='mentee_staff_member',
            new_name='mentee',
        ),
        migrations.RenameField(
            model_name='mentorshiprelationship',
            old_name='mentor_staff_member',
            new_name='mentor',
        ),
    ]
