# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0007_auto_20160422_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField()),
                ('mentor_response', models.CharField(choices=[('A', 'Accept'), ('D', 'Decline')], max_length=1)),
                ('mentee_response', models.CharField(choices=[('A', 'Accept'), ('D', 'Decline')], max_length=1)),
                ('cancelled_on', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_created', to='mentoring.StaffMember')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_invitations', to='mentoring.StaffMember')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_invitations', to='mentoring.StaffMember')),
                ('relationship', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentoring.MentorshipRelationship')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held_on', models.DateField()),
                ('approximate_duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MR', 'Mentor'), ('ME', 'ME')], max_length=1)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.StaffMember')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='mentoring.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held_on', models.DateField()),
                ('details_url', models.URLField(blank=True)),
                ('attendees', models.ManyToManyField(to='mentoring.StaffMember')),
            ],
        ),
    ]
