# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0008_invitation_meeting_meetingattendance_trainingevent'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='staffmember',
            managers=[
                ('current_members', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='mentorshippreferences',
            name='staff_member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership_preferences', to='mentoring.StaffMember'),
        ),
    ]
