# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 14:01
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0009_auto_20160423_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorshippreferences',
            name='id',
        ),
        migrations.AlterField(
            model_name='mentorshippreferences',
            name='is_seeking_mentee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mentorshippreferences',
            name='is_seeking_mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mentorshippreferences',
            name='staff_member',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mentorship_preferences', serialize=False, to='mentoring.StaffMember'),
        ),
    ]
