# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0010_auto_20160423_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
