# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0011_staffmember_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='is_current',
            field=models.BooleanField(),
        ),
    ]
