# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0012_auto_20160423_1419'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='staffmember',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='mentorshiprelationship',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentorshiprelationship',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_relationships', to='mentoring.StaffMember'),
        ),
        migrations.AlterField(
            model_name='mentorshiprelationship',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_relationships', to='mentoring.StaffMember'),
        ),
    ]
