# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0013_auto_20160424_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmember',
            old_name='is_current',
            new_name='is_active',
        ),
    ]
