# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 09:43
from __future__ import unicode_literals

from django.contrib.auth import get_user_model
from django.db import migrations

from cuedmembers import get_member_group

def set_group_membership(apps, schema_editor):
    """Set the group membership of CUED members correctly."""
    member_group = get_member_group()
    user = get_user_model()
    member_group.user_set.add(*user.objects.filter(cued_member__is_active=True))
    member_group.user_set.remove(*user.objects.filter(
        cued_member__is_active=False))

class Migration(migrations.Migration):

    dependencies = [
        ('cuedmembers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_group_membership),
    ]
