# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuedmembers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
