# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuedmembers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held_on', models.DateField()),
                ('details_url', models.URLField(blank=True)),
                ('attendees', models.ManyToManyField(to='cuedmembers.Member')),
            ],
        ),
    ]
