# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 07:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingevent',
            name='attendees',
            field=models.ManyToManyField(related_name='training_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
