# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_add_matchmake_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'permissions': (('matchmake', 'Can matchmake mentors and mentees with each other'),)},
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='relationship_started',
            new_name='created_relationship',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='cancelled_on',
            new_name='deactivated_on',
        ),
    ]
