# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_rename_invitation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='mentee_response',
            field=models.CharField(blank=True, choices=[('A', 'Accept'), ('D', 'Decline')], max_length=1),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='mentor_response',
            field=models.CharField(blank=True, choices=[('A', 'Accept'), ('D', 'Decline')], max_length=1),
        ),
    ]
