# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_remove_matchmake_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='is_active',
        ),
    ]
